const Users = [
    { id: "1", name: "Risma", fullname: "Risma Handayani", gender: "F" },
    { id: "2", name: "Rafi", fullname: "Rafi Maulana", gender: "M" },
    { id: "3", name: "Zahra", fullname: "Zahra Nabila", gender: "F" },
    { id: "4", name: "Kevin", fullname: "Kevin Hartanto", gender: "M" },
    { id: "5", name: "Nadia", fullname: "Nadia Prameswari", gender: "F" },
    { id: "6", name: "Fajar", fullname: "Fajar Ramadhan", gender: "M" },
    { id: "7", name: "Citra", fullname: "Citra Lestari", gender: "F" },
    { id: "8", name: "Adhimas", fullname: "Adhimas Dwi Putra", gender: "M" },
    { id: "9", name: "Rizky", fullname: "Rizky Ananda", gender: "M" },
    { id: "10", name: "Tasya", fullname: "Tasya Amanda", gender: "F" },
    { id: "11", name: "Alya", fullname: "Alya Rahmawati", gender: "F" },
    { id: "12", name: "Bagas", fullname: "Bagas Prasetyo", gender: "M" },
    { id: "13", name: "Dina", fullname: "Dina Mariana", gender: "F" },
    { id: "14", name: "Eko", fullname: "Eko Saputra", gender: "M" },
    { id: "15", name: "Farah", fullname: "Farah Khairunnisa", gender: "F" },
    { id: "16", name: "Gilang", fullname: "Gilang Perdana", gender: "M" },
    { id: "17", name: "Hana", fullname: "Hana Aulia", gender: "F" },
    { id: "18", name: "Iqbal", fullname: "Iqbal Maulana", gender: "M" },
    { id: "19", name: "Jihan", fullname: "Jihan Safira", gender: "F" },
    { id: "20", name: "Kiki", fullname: "Kiki Wulandari", gender: "F" },
    { id: "21", name: "Leo", fullname: "Leo Santoso", gender: "M" },
    { id: "22", name: "Maya", fullname: "Maya Salsabila", gender: "F" },
    { id: "23", name: "Niko", fullname: "Niko Ariyanto", gender: "M" },
    { id: "24", name: "Olive", fullname: "Olive Natalia", gender: "F" },
    { id: "25", name: "Pandu", fullname: "Pandu Wiratama", gender: "M" },
    { id: "26", name: "Qory", fullname: "Qory Azahra", gender: "F" },
    { id: "27", name: "Randy", fullname: "Randy Syahputra", gender: "M" },
    { id: "28", name: "Sinta", fullname: "Sinta Maharani", gender: "F" },
    { id: "29", name: "Tomi", fullname: "Tomi Nugraha", gender: "M" },
    { id: "30", name: "Ulya", fullname: "Ulya Fadhilah", gender: "F" },
  ];
  
  export default Users;
  